Lambda-School-Labs/human-rights-first-asylum-fe-a

src/components/pages/Login/LoginContainer.js
src/components/pages/Login/LoginContainerStyled.js
src/components/pages/SideDrawer/SideDrawer.js

The login page was completely restyled, I removed just the login button which redirected to the Okta sign in widget and instead had the widget display on the login page itself. I also edited the SideDrawer.js and made the "Human Rights First" header very slightly bigger.

Restyled login page and made the header on side drawer larger

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/SavedCases/SavedCases.js
src/components/pages/SavedJudges/SavedJudges.js

The headers on the Cases and Judges tables needed to be bold in order to give users a clear indication of what kind of data each column of the tables holds.

Made headers on cases and judges tables bold

---

src/components/pages/Upload/UploadCase.js

Found a bug where if a user successfully sends a file once, then attempts another upload but cancels in the dialog box, an empty file will be sent to the back end. Added a check to onFileChange to exit the function if the file is empty.

prevents sending empty file to backend if user cancels upload

---

src/components/pages/SideDrawer/SideDrawer.js

- If page was manually refreshed, side drawer would highlight 'Home' no matter what page you were on
- Set defaultSelecteKeys = {[window.location.pathname]} instead of {['/']}

changed defaultSelectedKeys of SideDrawer Menu to reflect current path

---

src/components/pages/CaseTable/CaseTable.js

Spotted an issue where the Judge column in the table on the cases page was trying to split a non-existent value to create a link to each judge's individual page. Fixed the bug, and added the ability to actually click into each JudgePage from the cases component.

fixes broken CaseTable component, adds link to JudgePage

---

src/components/pages/DataHub/DataHub.js
src/components/pages/DataHub/DataHub.less

This pull request removes unnecessary options from the Plotly chart's modebar as discussed. Also added a header for the datahub to describe the main chart - this is a placeholder until we get a real overview visualization in there.

Datahub table modebar

---

src/components/pages/Cases/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.js

changed judge/case table alerts to styled notifications.  Changed judge saving to judge_id vs first_name.
Judge bookmark tracking with first name instead switched to judge_id.

table alerts and post judge to judge id

---

src/components/pages/Login/LoginContainer.js

There was a bug that was causing the login page to crash if the Register Link was clicked and then the browser back button was clicked to go back to the login page.
Moved the widget out of the useEffect() for the login page so that remove() could be called on it when the Register Link is clicked (per okta documentation)

fixes okta register/back button whitescreen bug

---

src/components/pages/SideDrawer/MenuButton.js
src/components/pages/SideDrawer/SideDrawer.js

Getting DOM error from non-menu item in the side drawer:
React does not recognize the inlineIndent prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase inlineindent instead. If you accidentally passed it from a parent component, remove it from the DOM element.
Moved the collapse button to its own component to fix DOM error.

fixes DOM error of inlineIndent not recognized

---

src/components/pages/Cases/CaseTable.js
src/components/pages/Cases/CaseTable.less

Changed the Cases page table Case Details button from a Link without a destination to just use the icon as a link.
Also changed an axios catch from a console.log to throw new Error(err).
Added comment on bookmark function that it should be converted to an alert.
On the Cases page, the table Case Details button was producing a warning in the browser console about the <Link> component not having the required to='' completed (Link without a destination).

fixes <Link to=''> warning in browser

---

src/components/pages/Cases/PDFOverviewExport/ExportGenerator.jsx
src/components/pages/SavedCases/SavedCases.js

Added rowKey prop to the antd Table component in SavedCAses.js and added key prop to the View component caseData map in ExportGenerator.jsx
Getting unique key warnings in console due to antd Table rows missing keys.

fixes unique key warnings for saved cases

---

src/components/pages/AdminTools/ManageFaq.js

Added key prop to Panel component in ManageFaq.js
Getting unique key warnings in console due to FAQs missing key prop

fixes unique key warning on manage-faq page

---

src/components/pages/Upload/UploadCase.js

Added key prop to upload case modal footer
Upload cases modal was producing a unique key warning. Located issue was coming from the modal footer.

fixes modal footer key warning

---

src/components/pages/Home/RenderHomePage.js
src/components/pages/ManageCases/ManageCases.js

The ManageCases component was modified to follow the same pattern as the ManageUsers and ManageFaq components, both of which recieve authState as a prop and use the token to control the useEffect loop to load initial data. This is to prevent the useEffect in ManageCases from running in an infinite loop.
The useEffect function in the ManageCases component would run whenever filteredData changed, but the function itself was the only thing modifying filteredData. When the manage-cases page loaded, the useEffect would run in an infinite loop, making many GET requests to the API per second and storing the results. 
Fixes # ManageCases useEffect Loop

Bug/manage cases loop/rpeck

---

src/components/pages/AccountPage/AccountPage.js

There was a bug in the AccountPage.js component which would erase the role name displayed in the UI upon editing account details (on a successful PUT request). This update fixes that error by implementing several ternary checks to determine the appropriate role name that is to be rendered - these ternary checks reflect the recent updates to the role names in the backend ('admin', 'moderator', and 'user').

Fixes a UI bug in the AccountPage.js component

---

src/components/pages/Login/_LoginContainerStyled.less

Fixed the reset via email button text not being centered. The text is now centered.
Reset via email button text is now centered.
Type of change
Styling
Checklist:
[ x] My code follows the style guidelines of this project
[ x] I have performed a self-review of my own code
[x ] I have removed unnecessary comments/console logs from my code
[x ] I have made corresponding changes to the documentation if necessary (optional)
[x ] My changes generate no new warnings
[x ] I have checked my code and corrected any misspellings
[ x] No duplicate code left within changed files
[ x] Size of pull request kept to a minimum
[x ] Pull request description clearly describes changes made & motivations for said changes

centered reset email btn

---

src/utils/case_utils/case_columns.js

This is a quick addition to the codebase to realign the variables expected in the `case_columns.js` file in order to complete the merge of @AD9018's prior changes. This completes those changes by finally fixing the snafu around the legacy branch Adam was working with having been 101 commits behind `main`, ensuring that our table is expecting the variables being sent from the DS API to the Node back-end and finally to the front-end and is simply a renaming of fields.

quick case column variable alignment patch

---

src/components/pages/Login/_LoginContainerStyled.less

Co-authored-by: Secoya Wood <zionywood@outlook.com>
Co-authored-by: Dylan Rinella <rinelladylan@aim.com>
The login page needed to be adjusted to be responsive at all screen sizes. We did some short research to find out that 320px is the smallest screen size relevant to the industry standard. It is essential for this app to accessible on a mobile phone or tablet, and this ensures in the future that the layout of the login page is polished for those experiences. In order to solve this problem, we had to identify the different components and css classes needed to adequately display the login page on all relevant screen sizes.
[Trello Card](https://trello.com/c/vSOKNvFd)
[Loom](https://www.loom.com/share/c03ba73fd4bf4852b088bff4f9ea338b)
Makes the login page responsive at all …

Styling of Login Page to Accommodate all screen sizes down to 320px

---

src/components/pages/Login/_LoginContainerStyled.less

On the login page the custom checkbox was getting a box-shadow border around the container it was in and the source was relatively tricky to track down but it eventually was found and the code we added although simple fixed the problem we were having. 
[Loom](https://www.loom.com/share/82e7c7b922d4496eaa483e04f4e8fd32)
-Contributors-
@ctscofield 
@RickyKlusmeier 
@willmoon19 
@lucaschatham 
- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] I have removed unnecessary comments/console logs from my code
- [y] My changes generate no new warnings
- [y] I have checked my code and corrected any misspellings
- [y] No duplicate code left within changed files
- [y] Size of pull request kept to a minimum
- [y] Pull request …

fixed box-shadow around custom-checkbox div

---

src/components/pages/Cases/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/JudgeTable/_JudgeTableStyles.less

This started as a ticket having us change the word "filter" to "save" in the search model. It then came up that it was not very intuitive to save a judge or case with the bookmark icon.
[Trello](https://trello.com/c/eBwSU8Tf)
[Loom](https://www.loom.com/share/ebd846e9205e4b48817f81c073a81304)
The first fix was changing "filter" to "save" in the search model.
The second fix was to change the bookmark icon into a save button. In order to make it a little more intuitive, I disabled the button when nothing is checked, then when you check a box the button will become enabled and change from a light grey to blue using a ternary and adding another slice of state.

replaced bookmark icon with a save button and changed "filter" to "save" in the search model

---

src/components/pages/MyCases/ReviewCaseForm.js
src/components/pages/MyCases/ReviewCaseForm.less

Co-authored-by: Secoya Wood <zionywood@outlook.com>
We have implemented a way to highlight fields that render empty upon the mounting of this component. This was requested by the Stakeholder, and is important and necessary because the user is prompted to fill the Review Case Form when a case uploads without having all of the data properly scraped. With this change, the user will be able to quickly see which fields did not populate as soon as the component mounts and renders.
[Trello Ticket](https://trello.com/c/0xuhntTo)
[Loom Video](https://www.loom.com/share/b96a58db3ba84062b1a48e698d642fa3)

Implemented Warning Label for Review Case Form
