Lambda-School-Labs/human-rights-first-asylum-fe-a

src/components/pages/CaseTable/CaseTable.js

Forgot to make search case insensitive. Fixed.

Search bug fix

---

src/components/pages/CaseOverview/CaseOverview.js
src/components/pages/CaseOverview/CaseOverviewStyled.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/PDFViewer/PDFViewer.js
src/components/pages/PDFViewer/PDFViewerStyled.js
src/globalStyles.js
src/index.js

- What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
- Added GlobalStyles from 'styled-components' and implemented CSS reset
- Reconfigured Dashboard and PDF Viewer interface
- https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da

PDF Viewer interface

---

src/components/pages/Home/RenderHomePage.js
src/components/pages/PDFViewer/PDFViewer.js
src/components/pages/PDFViewer/PDFViewerStyled.js
src/utils/useWindowDimensions.js

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
- Reconfigured the user interface for PDF Viewer
- https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da

Reconfigured user interface for PDF Viewer

---

src/components/pages/Home/RenderHomePage.js
src/components/pages/PDFViewer/PDFViewerStyled.js

```
[x] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
- Quick styling bug on PDF Viewer
- Fixed merge conflict error in Main repository
- https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da

Bug Fix and Merge Conflict Error in Main

---

package-lock.json
package.json
src/components/pages/Home/RenderHomePage.js

In order to make user experience positive, this pull request implements a spinning loader to inform the user that the table information is being loaded in rather than it just being a blank screen.

Added a spinning logo while information loads into the tables

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/JudgePage/JudgePage.js
src/components/pages/JudgeTable/JudgeTable.js

This feature changes all hardcoded endpoints to the heroku endpoints using the .env file.

Changed all hardcoded endpoints to .env heroku endpoints

---

src/components/pages/Home/RenderHomePage.js

Forgot to comment out upload case import.

Commented out import of upload case

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/JudgePage/JudgePage.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/SideDrawer/SideDrawer.js

Connected Judge Table with Judge Page(profile), sidebar stays on page unless the user closes it (per stakeholder)

Updated UI ab

---

src/components/pages/CaseTable/CaseTable.js

Adds refugee credibility field to CaseTable file

Adds regugess credibility field to CaseTable

---

src/components/pages/CaseTable/CaseTable.js

PSG field name changed, column width modified

modifys the table

---

package-lock.json
package.json
src/components/pages/Home/HomeContainer.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/SideDrawer/SideDrawer.js
src/index.js

updated Okta 3.0.2 to Okta 5.0.0 by changing authentication methods from Okta and Axios calls

updated Okta 3.0.2 to Okta 5.0.0

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.js

fixed searching bug and set default columns on each render

Added options bar for table customization

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/SideDrawer/SideDrawer.js

Added custom toolbar to Datagrid, commented out the filter and save cases buttons for the time being, added nav items for cases and judge table.

Implementing design suggestions from David

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/SideDrawer/SideDrawer.js

changed calls for bookmarking cases but waiting on backend changes to completely fix it

Saved items fixes and search algorithm rework

---

src/components/pages/SupportPage/SupportPage.js

Please let me know if any of the language needs changing or any other FAQ's that may need to be added.

Filled out the answer portion of the FAQ

---

src/components/pages/SideDrawer/SideDrawer.js

Design feature that client wanted.
App bar no longer has shadow, has bottom border instead.

Side drawer stays open outside of small breakpoint

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/SideDrawer/SideDrawer.js

Some of the MUI component props and 1 className prop were throwing some console errors. This is just to fix those.

Fix of some MUI console errors

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/Home/HomeContainer.js
src/components/pages/SideDrawer/SideDrawer.js

App bar and side drawer were not correctly rendering on smaller screen.
This branch fixes that bug and allows the menu icon to render and be clicked.
Breakpoint based on iPad px.

Fix/menu bug fix/christina

---

src/components/pages/Login/LoginContainer.js
src/components/pages/Login/LoginContainerStyled.js

Just some small adjustments to get rid of some weird white space and make the page more responsive

Styling fixes for the login page

---

src/components/pages/Upload/UploadCase.js

Was tasked with adding a simple alert for when a case is uploaded.

adds alert after case is uploaded, for video purposes

---

src/components/pages/CaseTable/CaseTable.css
src/components/pages/Home/HomeContainer.js

I think that's the last of the MUI blue converted to HRF blue

MUI Color fixes

---

src/components/pages/CaseTable/CaseTable.js
src/components/pages/CaseTable/PDFOverviewExport/ExportGenerator.jsx
src/components/pages/CaseTable/PDFOverviewExport/PDFExportButton.js

button is styled and pdf rows now filter according to search queries

button is styled and pdf rows now filter according to search queries

---

src/components/pages/CaseOverview/CaseOverview.js
src/components/pages/CaseTable/CaseTable.js

- This PR reconfigures the code that sends the token
- Previous code with {authState} from props was removed because it was returning undefined

sends token with request, for auth purposes

---

src/components/pages/CaseTable/CaseTable.css
src/components/pages/CaseTable/CaseTable.js

I moved CSS from the case table into its own file.
I will add in Juan's fixes for the drawer, I have the specs still.

moved css to its own file

---

src/components/pages/CaseTable/CaseTable.js

Fixing the case table linting errors

Fixing case table lint errors

---

src/components/pages/SupportPage/SupportPage.css
src/components/pages/SupportPage/SupportPage.js

first panel defaults to open, panels also close when another is opened

---

src/components/pages/CaseTable/CaseTable.js

- Tabs were moved inside table yesterday
- This code styles them to fit the table aesthetic
- Got rid of unnecessary code
https://user-images.githubusercontent.com/71955286/116295893-7066b900-a74e-11eb-823e-4dc1ecbfa837.mov

updates styles for tabs, cleans up code

---

src/components/pages/CaseTable/CaseTable.css
src/components/pages/CaseTable/CaseTable.js
src/components/pages/JudgePage/JudgePage.css
src/components/pages/JudgePage/JudgePage.js

Fixed the moving search icon when hovering.
Fixed the export button in dropdown, only has 1 icon now.
Fixed the judge card page so the menu matches other menus.

fixed case table menu to render correctly

---

src/components/pages/AccountPage/AccountPage.css
src/components/pages/AccountPage/AccountPage.js

Added a CSS file to account component.
Added Ant Design to the account component.

added styling to account page and css file

---

src/components/pages/Home/RenderHomePage.js
src/components/pages/Upload/UploadCase.js

Just updating the upload stuff to use auth properly, gotta have security :)

Adding auth to upload stuff

---

src/components/pages/Upload/UploadCase.js
src/components/pages/Upload/UploadCaseForm.js

- Able to select multiple files to upload
- Added drag and drop component for better usability (using ant-design)
- Converted uploading component into a pop up modal (using ant-design)

New Feature: Bulk Case Upload 

---

src/components/pages/CaseOverview/CaseOverview.js
src/components/pages/CaseTable/CaseTable.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/SideDrawer/SideDrawer.js
src/components/pages/SupportPage/SupportPage.js

- The user can easily track where they are in the application based on color of the navbar
- Warnings were resolved by adding a key when using map function 
- Warnings were resolved by removing unused lines of code 
- Comments were changed to clarify purpose of code (namely, styling in RenderHomePage)

Tabs are styled based on active component; resolved misc warnings 

---

src/components/pages/Home/RenderHomePage.js

- fixed upload queue (it actually works now)

fixed upload bug

---

src/components/pages/CaseTable/CaseTable.css
src/components/pages/CaseTable/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.css
src/components/pages/JudgeTable/JudgeTable.js

Implements style changes matching the Judges table to the Cases Table.

implements style changes to the cases table

---

src/components/pages/Home/MainHeader.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/Home/_MainHeader.less
src/components/pages/SideDrawer/SideDrawer.js

- changed side drawer from MUI to Ant D 
- sub-menus open by default for ease of access
- account icon placeholder added on header

changes side drawer tand header to follow styling guidelines

---

src/components/pages/SideDrawer/SideDrawer.js

- sidebar only makes one selection active at a time

fixed bug so that only one section is active at a time

---

src/components/pages/CaseTable/CaseTable.css
src/components/pages/CaseTable/CaseTable.js
src/components/pages/CaseTable/CaseTable.less

This pull changes the data visualization on the cases page from a pie chart (ew) to a pair of bar charts for now. Additionally makes changes to the CSS for this page to display them appropriately.

adds new data visualizations to Cases page, makes fixes for style

---

src/components/pages/JudgeTable/JudgeTable.js

- correctly adds selected judges to be sent to backend 
- checks against no selection with appropriate alert 
- Need to fix backend to complement POST request given. Currently, backend is running into a error with database where a new migration may be able to fix this error.

adds judges that are selected via  POST request on frontend

---

src/components/pages/JudgeTable/JudgeTable.js

judge name bug fix

---

src/utils/axiosWithAuth.js

Added an axiosWithAuth utility function. The plan is to replace all the redundant axios calls in all of the components.

adds an axiosWithAuth function to begin refactoring axios calls

---

src/components/pages/AdminTools/AddFaq.js
src/components/pages/AdminTools/ManageFaq.js
src/components/pages/AdminTools/_FaqStyles.less
src/components/pages/AdminTools/_ManageFaqStyles.less
src/components/pages/SideDrawer/SideDrawer.js
src/components/pages/SideDrawer/_SideDrawer.less
src/components/pages/Upload/_UploadCase.less

Merged the "Add a FAQ" with the "Manage Faq" component. Converted the elements to Ant D and added the "Add a Faq" to a modal. Removed the "add a FAq" from the side nav. 
Fixes # 
I fixed some styling bugs that were affected when global style tags were used.

Feature/merge admin tools-FAQ

---

src/components/pages/MyCases/MyCases.js
src/components/pages/MyCases/ReviewCaseForm.js

- previous form inputs were being re-rendered excessively with input changes (noticeable lag in typing) which is now fixed
- cleaned up the form state

fixed form excessive re-renders

---

src/components/pages/Home/MainHeader.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/Upload/_UploadCase.less

- upload case is now moved to the header

moved upload case to header

---

src/components/pages/AdminTools/EditUser.js
src/components/pages/AdminTools/ManageUsers.js

- admin can create, edit, delete user
- CRUD operations are successful locally, but will need to check Okta to verify that CRUD is completed in that db

admin can add, update, delete user from frontend

---

src/components/pages/CaseTable/CaseTable.js

Quick fix. Date in the Cases page was not working.
Changed date to case_date where needed.

fixing dates on CaseTable to match backend

---

src/components/pages/AdminTools/ManageUsers.js
src/components/pages/AdminTools/PendingUsers.js
src/components/pages/Login/SignupPage.js

- updated firstName & lastName fields to first_name & last_name in forms
- updated state of MangeUsers & PendingUsers components on Accept, Reject
- fixes inability to type in signup and edit user forms
- verifies flow of user operations with backend and Okta
- still need to update state after edit user submit
- edit user form should be modal instead of its own page/route

User Registration Fixes

---

src/components/pages/MyCases/MyCases.js

- added progress bar on My Cases:

added progress bar to reflect upload case for 4 possible statuses

---

src/components/pages/AccountPage/_AccountPageStyles.less
src/components/pages/SupportPage/_SupportPageStyles.less

-Edited account and support to fit with side nav and added top margin.

Updated containers to fit with nav

---

src/components/pages/DataHub/DataHub.less
src/components/pages/JudgePage/JudgePage.less

This fixes the home page and the individual judge page to also fit with the fixed sidebar.

Fix home container

---

src/components/pages/Home/RenderHomePage.js

- missing 2nd step of removing EditUser page

Bug fix for Edit Users page removal

---

src/components/pages/Cases/CaseTable.js
src/components/pages/Cases/CaseTable.less

-Updated the rest of the styling for the case table. 
-Created a component for the save button in order to be reused on each tab. 
Notes:
- Unable to get the tabs fixed when scrolling
- We still need the case details button to work 
- We need the judge names to link to the judge page

completed styling for case table

---

src/components/pages/AdminTools/_ManageFaqStyles.less
src/components/pages/Home/RenderHomePage.js
src/components/pages/SavedCases/SavedCases.js
src/components/pages/SavedCases/_SavedCasesStyles.less
src/components/pages/SavedJudges/SavedJudges.js
src/components/pages/SavedJudges/_SavedJudgesStyles.less

- changed saved cases and judges table from MUI to Ant D
Note: Will be going back in to change case number column to 'view case' with icon

changed saved cases and judge components from MUI to Ant D

---

src/components/pages/Cases/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/JudgeTable/_JudgeTableStyles.less

Transitioned judges table to antD.  added column sort and filter, fixed judge name render and date render.  Adjusted column search placeholder on case table and judge table.

Judge table converted to antD

---

src/components/pages/Cases/CaseTable.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/Home/_MainHeader.less
src/components/pages/ManageCases/ManageCases.js
src/components/pages/SavedCases/SavedCases.js
src/components/pages/SavedCases/_SavedCasesStyles.less
src/components/pages/SavedJudges/SavedJudges.js
src/components/pages/SavedJudges/_SavedJudgesStyles.less

- user can successfully save cases 
- there is only one success message instead of the same amount as cases saved
- header made to fit 100% screen width
- user can access pdf to the saved case
- more relevant information displayed on save judge and case table

saved judges and cases functionality and styled components

---

src/components/pages/Cases/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/JudgeTable/_JudgeTableStyles.less

-adjusted styling to the Judge Table
-Added tab to the table to keep styling consistent to match case table
Notes:
- We still need the judge names to link to the judge page

corrected styling on judge table

---

src/components/pages/Cases/CaseTable.js
src/components/pages/Cases/CaseTable.less
src/components/pages/DataHub/DataHub.js
src/components/pages/DataHub/DataHub.less
src/components/pages/JudgePage/JudgePage.js
src/components/pages/JudgePage/JudgePage.less
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/JudgeTable/_JudgeTableStyles.less

This update:
- Fixes broken judge page links on case and judge tables
- Removes extra mock visualizations, fine-tunes the styling on the relevant visualizations
- Adds matching headers to all components
Table links for judges now work.

Viz tuneup

---

src/components/pages/AccountPage/AccountPage.js

- user can edit information from account info page through a modal 
Note: need to rerender the page to see result. Need to fix method of updating

added modal to edit user info

---

src/components/pages/Cases/CaseTable.js
src/components/pages/MyCases/ReviewCaseForm.css
src/components/pages/MyCases/ReviewCaseForm.js
src/components/pages/MyCases/ReviewCaseForm.less

- converts MUI form on review cases upload to AntD

converts MUI form to AntD

---

src/components/pages/Cases/CaseTable.js

- [x I have performed a self-review of my own code

deleted duplicate import of orangeline on table

---

src/components/pages/AdminTools/PendingUsers.js
src/components/pages/Login/SignupPage.js

- replaces axiosWithAuth with axios call to fix signup bug
- resets state of pending profiles on manage profiles correctly to fix rerender
- adds antD success & error notifications to signup page
- request access errors out on signup page
- all pending profiles disappear on reject

Signup Flow Fixes

---

README.md

- Added postgreSQL set up to the instructions (link to Lambda page with instructions)
- Add the visualization endpoint that interacts with the DS API to the readm

Add set up postgreSQL instructions to readme

---

src/components/pages/Home/MainHeader.js
src/components/pages/Home/_MainHeader.less

- The human rights first logo is no longer distorted
- The "Upload A Case" button was repositioned next to the account icon as discussed during product reviews
- Bug fix/UI fix
The height of `MainHeader.js` was slightly decreased as a side effect. Personally, I think it looks better as the nav looked bulky before, but I will leave it to the design leads to approve or decide to keep the previous height. @nicholasbus @CatRadin @emmac124 
Next, I want to increase the size of the account icon logo as it looks a bit too small currently.

fixes logo distortion on MainHeader.js and repositions UploadCase button next to the account icon

---

src/components/pages/Cases/PDFOverviewExport/ExportGenerator.jsx
src/components/pages/Cases/PDFOverviewExport/PDFExportButton.js
src/components/pages/SavedCases/SavedCases.js

Got export report function working and tentatively put it in the Saved Cases component table.
Function is basic at the moment and only includes a limited amount of case data without any visualizations.
Additional direction from stakeholders required to produce a meaningful report.
Created new column in Saved Cases Table to hold download button in SavedCases.js.
Changed Download Link to a Download Button in PDFExportButton.js to save space in table.
Added variables to convert UTC case_date received from database to a locally formatted date in ExportGenerator.jsx.

Gets export report functions working

---

src/components/pages/CaseOverview/CaseDetails.js
src/components/pages/CaseOverview/CaseOverview.js
src/components/pages/CaseOverview/CaseUpdate.js
src/components/pages/CaseOverview/EditCaseDetails.js
src/components/pages/Cases/CaseTable.js
src/components/pages/Cases/PDFOverviewExport/ExportGenerator.jsx
src/components/pages/DataHub/DataHub.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/JudgePage/JudgePage.js
src/components/pages/ManageCases/ManageCases.js
src/components/pages/MyCases/MyCases.js
src/components/pages/MyCases/ReviewCaseForm.js
src/components/pages/SavedCases/SavedCases.js

- Fixed the naming conventions to better match the new backend schemas

Changed the naming conventions to better align with new back end schemas

---

src/components/pages/JudgeTable/JudgeTable.js

Added filtering indication to the judges table. Filtering indication system is very similar to the system being used on the cases page

added filter indication to the judge table

---

src/components/pages/Login/SignupPage.js
src/components/pages/Login/_LoginContainerStyled.less

Changed wording on register page so button and header where the same, as well as centered the "need help signing in?" links.

Feature/register page UI edit

---

src/components/pages/AdminTools/AddFaq.js
src/components/pages/CaseOverview/CaseDetails.js
src/components/pages/CaseOverview/CaseOverview.js
src/components/pages/CaseOverview/CaseUpdate.js
src/components/pages/Cases/CaseTable.js
src/components/pages/DataHub/DataHub.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/ManageCases/ManageCases.js

Cleaned up some console.logs and code that wasn't being used

Cleaned up a few console logs and added useEffect dependencies

---

src/components/pages/CaseOverview/CaseDetails.js

The case details window was improperly displaying the date
The date is now displayed in a readable format

Fixed the date to display properly on case details

---

src/components/pages/AccountPage/AccountPage.js

Fixes an issue where, on the My Account page, submitting an edit to the account details would not properly reflect the changes made to the currently logged in account (the bug would instead display the data for llama010)

Fixes an issue in the AccountPage.js file

---

src/components/pages/JudgeTable/_JudgeTableStyles.less

Bug fix on _JudgeTableStyles.less
The judge table .less file wasn't properly using ant design

fixed a bug where the judge table css wasn't using ant design

---

src/components/pages/DataHub/DataHub.js
src/components/pages/DataHub/DataHub.less

As requested by our stakeholders, this update adds a simple (non-intrusive) disclaimer message to the home page to provide ethical context to the visualized data. The colors utilized were pulled from the application's theme, and they do not clash or otherwise interfere with the UI.

Added disclaimer message to the Home page (DataHub.js component and its associated style sheet)

---

src/components/pages/JudgePage/JudgePage.js
src/components/pages/JudgePage/JudgePage.less

As requested by our stakeholders, the top of each individual judge's information page now contains a disclaimer which provides ethical context for the data which is to be visualized on the page.

Added a disclaimer message to the top of the JudgePage.js component

---

src/components/pages/CaseOverview/CaseDetails.js

As requested by the stakeholders, the popup modal window containing a specific case's details now also contains a disclaimer message at the bottom which provides further ethical context.

Adds a disclaimer message to the CaseDetails modal window

---

KnownDefects.md

This is an update for KnownDefects.md about CaseTable.js so that the incoming team can work on this error without having to start from the beginning.

creating documentation for a known defect on the CaseTable page

---

README.md
src/components/pages/AccountPage/AccountPage.js
src/components/pages/CaseOverview/CaseDetails.js
src/components/pages/DataHub/DataHub.js
src/components/pages/JudgePage/JudgePage.js

Added inline comments to the AccountPage.js, CaseOverview.js, DataHub.js, and JudgePage.js components; added additional documentation notes to the README.md file

Added inline comments to various components, and additional documentation to README.md

---

src/components/pages/CaseOverview/CaseDetails.js
src/components/pages/JudgePage/JudgePage.js

My last update contained an error in the inline comments in the CaseDetails.js component and the JudgePage.js component. This PR corrects that mistake.

Fixes an error in the inline comments from my last update (in the CaseDetails.js and JudgePage.js components)

---

src/components/pages/DataHub/DataHub.js

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have removed unnecessary comments/console logs from my code
- [ x ] I have made corresponding changes to the documentation if necessary (optional)
- [ x ] My changes generate no new warnings
- [ x ] I have checked my code and corrected any misspellings
- [ x ] No duplicate code left within changed files
- [x ] Size of pull request kept to a minimum
- [ x ] Pull request …

removes orange bar from homepage

---

src/components/pages/DataHub/DataHub.js
src/components/pages/DataHub/DataHub.less

Removed the double border from the homepage text that our team agreed wasn't visually pleasing
Fixes # (border)
- [ x ] Design
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have removed unnecessary comments/console logs from my code
- [ x ] I have made corresponding changes to the documentation if necessary (optional)
- [ x ] My changes generate no new warnings
- [ x ] I have checked my code and corrected any misspellings
- [ x ] No duplicate code left within changed files
- [ x ] Size of pull request kept to a minimum
- [ x ] Pull request description clearly describes changes made & motivations for said changes

Removes double boarder

---

src/components/pages/DataHub/DataHub.js

1 Changes VS to vs on the data hub display
Just fixed a small casing error
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have removed unnecessary comments/console logs from my code
- [ x] I have made corresponding changes to the documentation if necessary (optional)
- [ x] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings
- [ x] No duplicate code left within changed files
- [ x] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & …

Changed VS to vs in dataHub.js

---

src/components/pages/AdminTools/ManageUsers.js

Changed "profiles.user_id" to "profile.user_id" in "ManageUsers.js" in "AdminTool folder" to allow the front end to pass user_id properly to the backend.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have removed unnecessary comments/console logs from my code
- [ x] I have made corresponding changes to the documentation if necessary (optional)
- [x ] My changes generate no new warnings
- [x ] I have checked my code and …

profiles.user_id changed to profile.user_id

---

src/components/pages/DataHub/DataHub.js
src/components/pages/Home/MainHeader.js

removes orange line and makes account logo a link to account route
Styling 
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have removed unnecessary comments/console logs from my code
- [ x ] I have made corresponding changes to the documentation if necessary (optional)
- [ x ] I have checked my code and corrected any misspellings
- [ x ] No duplicate code left within changed files
- [ x ] Size of pull request kept to a minimum
- [ x ] Pull request description clearly describes changes made & motivations for said changes

removes orange line and makes account logo a link to account route

---

src/components/pages/AdminTools/PendingUsers.js

Previously, accepting a user as an admin didn't work. I fixed that functionality
1

fixed approve user bug

---

src/components/pages/AdminTools/PendingUsers.js

This was a bug fix I worked on with Alex Tran.
A post request, should have been a put request to a different endpoint

bug fix in Pending Users fixed

---

src/components/pages/SupportPage/SupportPage.js

This was already approved however, there were some odd things going on with files being deleted that I don't know how they were deleted, so I had to re-make this.
Fixed the contact us not working.
2 issues where code was incorrectly named leading to faulty code.

bug fixes to support.js

---

src/components/pages/Upload/_UploadCase.less

changed not now button background color

---

src/components/pages/CaseOverview/EditCaseDetails.js
src/components/pages/Cases/CaseTable.js
src/components/pages/ManageCases/ManageCases.js

fixed the no date issue

---

src/components/pages/Cases/CaseTable.js
src/utils/case_utils/case_columns.js
src/utils/filter_keyword_utils.js

This fix takes care of the issue where we are not able to search by date, the date object recognizes "-" (dashes) but we need to be able to search by how the data comes from the backend which would be using "/" instead. The user(s) can now search by date in any format(without the year as well). 
This fix just offers the user one more way to search and narrow down results depending on his/her criteria. 
https://www.loom.com/share/443f1981dcd449d780e4822fae8dc579

fixedDateBug-Thanks2BackEnd

---

src/components/pages/SideDrawer/SideDrawer.js
src/components/pages/SideDrawer/_SideDrawer.less

Added a button that collapses the side drawer leaving the icons there for the user to see as well as giving them more space
Co-Authored-by: @ctscofield 
[Trello](https://trello.com/c/RogihNTZ)
[Loom](https://www.loom.com/share/9ee8eea1f2174ec282f1abefa1f48305)

Added collapsing feature to side drawer

---

src/components/pages/SideDrawer/_SideDrawer.less

Co-authored-by: Cory Scofield <ctscofield@gmail.com>
[Trello](https://trello.com/c/OWNdGA8N)
[Loom](https://www.loom.com/share/844843c9e3ad48a3862fc0782d3359e7)
Video will help make this more clear
I added this commit to the original branch I was working on and it got pushed to main without getting approved. I am making this pull request so we can all see the changes and to make a record of them.
Added new styling to the Side Drawer component. Got rid of the absolute position and the bottom styling on the .collapseButton on line 198.
changed styles of the icons from lines 31 - 87, adjusting the left styling pixel sizes from 26px to 31px on line 32 and 35 and then changing the left styling of lines 41 - 74 from 20px to 26px. Also adjusted each words padding on the side Drawer, in order to …

refactored the style on the side drawer.

---

src/components/pages/Cases/CaseTable.js
src/components/pages/JudgeTable/JudgeTable.js
src/components/pages/JudgeTable/_JudgeTableStyles.less

Co-authored-by: Cory Scofield <ctscofield@gmail.com>
[Trello](https://trello.com/c/S2Qtb9jG)
[Loom](https://www.loom.com/share/ac77bea7a45b4de4b24beeb393e13415)
Made the filter bar more intuitive by moving it away from the save checkboxes. updated UI of the filter box and the filters themselves, making them much more visible when added as well as making the "X" (delete) button on on the individual filters more distinct.

adjusted filter bar and individual filter.
